### ISSUE TITLE
Support for GeoIP and domains

### ISSUE THREAD

**Issue by talentlessguy** [nodauf/Go-RouterSocks#38]
Hello, thanks for creating this tool. So far this is the only out of many I tried that actually worked with routing SOCKS traffic. Would be super cool if it would also support routing by GeoIP and not only CIDR.

For example:

```
> route add th 127.0.0.1:1234
```

would make all GeoIP from Thailand proxy through port :1234

**Comment by nodauf** [comment]
Hi,
Thank you for your kind words. I like your idea, I will certainly try to implement it.

**Comment by nodauf** [comment]
Could you try with the latest commit? I've run a few tests locally and it should work. However, I don't use it any more and I may not have taken certain scenarios into account. 
If you find any bugs, don't hesitate to report them and I'll fix them.

**Comment by nodauf** [comment]
It should be good. If you have any  issues feel free to open one.
